### ISSUE TITLE
Font Size (Height and Width) for MAX 7219 Library

### ISSUE THREAD

**Issue by pdrpatnaik** [markruys/arduino-Max72xxPanel#2]
How to increase the font height if for instance 4X(8*8) LED matrices are involved in displaying ticker using this library https://github.com/markruys/arduino-Max72xxPanel

**Comment by markruys** [comment]
The sixth argument of matrix.drawChar is an integer which defines the font size. 1 is default, 2 twice as big etc.

**Comment by pdrpatnaik** [comment]
Hey markruys,

I find no words to say thanks to your contribution to write that library. I
have been working with many like pandaboard, raspberry and arduino since 4
years and I knew how hard it is to grow up a library thats so user friendly
to use.

And special thanks to your quick reply.

Thank you.

Prof. P.D.R. Patnaik.
(Arduino Hobbyist)

**Comment by markruys** [comment]
Thank you for your kind words. I use so many other open source software that I'm glad I can contribute a bit.
